### ISSUE TITLE
Supply collection process presumes normal quality construction robots are available

### ISSUE THREAD

**Issue by hikeonpast** [tburrows13/SpidertronPatrols#12]
I'm using the mod via Maraxsis.  The process of collecting supplies to build ghosts assumes that normal quality bots are available on the logistic network.  The workflow seems to request normal quality construction robots even if the entity (spidertron/submarine) has higher quality construction robots pre-installed.

It doesn't seem like a Maraxsis-specific scenario that there are only higher quality construction robots available on the network, since this is a mid/late game mod, so posting the issue here.

**Comment by tburrows13** [comment]
I think this should be reported at https://mods.factorio.com/mod/Constructron-Continued rather than here? This mod only does the schedules and docks, not auto-requesting or auto-building.

**Comment by ILLISIS** [comment]
Hi @hikeonpast 

I am the coder of Constructrons.

The quality of the robot can be changed int eh settings UI via the mod button or SHIFT +C +C.
